from __future__ import annotations

import io
import json
import os
import queue
import struct
import subprocess
import sys
import threading
import time
import urllib.error
import urllib.request
import uuid
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from typing import BinaryIO

import mini_url_converter as core


HOST_NAME = "com.miniurlconverter.auth"
EXTENSION_ID = "blibefgifoccgdhbhahjapmffhmamjma"
BRIDGE_HOST = "127.0.0.1"
BRIDGE_PORT = 16688
BRIDGE_BASE_URL = f"http://{BRIDGE_HOST}:{BRIDGE_PORT}"
BRIDGE_DIR = core.APP_DATA_DIR / "chrome_bridge"
BRIDGE_COOKIE_PATH = core.APP_DATA_DIR / "cookies" / "chrome-live-cookies.txt"
NATIVE_MANIFEST_PATH = BRIDGE_DIR / f"{HOST_NAME}.json"
YOUTUBE_COOKIE_DOMAINS = (".youtube.com", ".google.com")


def extension_dir() -> Path:
    if getattr(sys, "frozen", False):
        return Path(sys.executable).resolve().parent / "chrome_extension"
    return core.DEV_PROJECT_ROOT / "chrome_extension"


def native_host_executable() -> Path:
    if getattr(sys, "frozen", False):
        return Path(sys.executable).resolve().parent / "chrome_native_host.exe"
    return core.DEV_PROJECT_ROOT / "dist" / "chrome_native_host.exe"


def _safe_cookie_text(value: object) -> str:
    return str(value or "").replace("\t", " ").replace("\r", "").replace("\n", "")


def _allowed_cookie_domain(domain: str) -> bool:
    normalized = domain.lower().lstrip(".")
    return normalized == "youtube.com" or normalized.endswith(".youtube.com") or normalized == "google.com" or normalized.endswith(".google.com")


def serialize_netscape_cookies(cookies: list[dict[str, object]]) -> str:
    dedup: dict[tuple[str, str, str], dict[str, object]] = {}
    for cookie in cookies:
        domain = _safe_cookie_text(cookie.get("domain"))
        path = _safe_cookie_text(cookie.get("path")) or "/"
        name = _safe_cookie_text(cookie.get("name"))
        if not domain or not name or not _allowed_cookie_domain(domain):
            continue
        key = (domain, path, name)
        current = dedup.get(key)
        current_expiry = float(current.get("expirationDate", 0) or 0) if current else -1.0
        candidate_expiry = float(cookie.get("expirationDate", 0) or 0)
        if current is None or candidate_expiry >= current_expiry:
            dedup[key] = cookie

    lines = ["# Netscape HTTP Cookie File", "# Generated by Mini URL Converter Chrome bridge", ""]
    for key in sorted(dedup):
        cookie = dedup[key]
        domain = _safe_cookie_text(cookie.get("domain"))
        path = _safe_cookie_text(cookie.get("path")) or "/"
        name = _safe_cookie_text(cookie.get("name"))
        value = _safe_cookie_text(cookie.get("value"))
        include_subdomains = "TRUE" if domain.startswith(".") else "FALSE"
        secure = "TRUE" if bool(cookie.get("secure")) else "FALSE"
        try:
            expires = max(0, int(float(cookie.get("expirationDate", 0) or 0)))
        except (TypeError, ValueError):
            expires = 0
        rendered_domain = f"#HttpOnly_{domain}" if bool(cookie.get("httpOnly")) else domain
        lines.append(
            "\t".join(
                (
                    rendered_domain,
                    include_subdomains,
                    path,
                    secure,
                    str(expires),
                    name,
                    value,
                )
            )
        )
    return "\n".join(lines) + "\n"


def _write_cookie_file(cookies: list[dict[str, object]]) -> tuple[Path, int]:
    text = serialize_netscape_cookies(cookies)
    useful_count = max(0, len([line for line in text.splitlines() if line and not line.startswith("#")]))
    BRIDGE_COOKIE_PATH.parent.mkdir(parents=True, exist_ok=True)
    temporary = BRIDGE_COOKIE_PATH.with_suffix(".txt.new")
    temporary.write_text(text, encoding="utf-8", newline="\n")
    os.replace(temporary, BRIDGE_COOKIE_PATH)
    return BRIDGE_COOKIE_PATH, useful_count


def encode_native_message(message: dict[str, object]) -> bytes:
    payload = json.dumps(message, ensure_ascii=False, separators=(",", ":")).encode("utf-8")
    return struct.pack("<I", len(payload)) + payload


def read_native_message(stream: BinaryIO) -> dict[str, object] | None:
    header = stream.read(4)
    if not header:
        return None
    if len(header) != 4:
        raise EOFError("Incomplete native-messaging header")
    length = struct.unpack("<I", header)[0]
    if length > 16 * 1024 * 1024:
        raise ValueError("Native-messaging payload is too large")
    payload = stream.read(length)
    if len(payload) != length:
        raise EOFError("Incomplete native-messaging payload")
    decoded = json.loads(payload.decode("utf-8"))
    if not isinstance(decoded, dict):
        raise ValueError("Native-messaging payload must be a JSON object")
    return decoded


class BridgeState:
    def __init__(self, output: BinaryIO) -> None:
        self.output = output
        self.write_lock = threading.Lock()
        self.pending_lock = threading.Lock()
        self.pending: dict[str, queue.Queue[dict[str, object]]] = {}
        self.extension_seen = threading.Event()

    def send(self, message: dict[str, object]) -> None:
        encoded = encode_native_message(message)
        with self.write_lock:
            self.output.write(encoded)
            self.output.flush()

    def handle_extension_message(self, message: dict[str, object]) -> None:
        message_type = str(message.get("type", ""))
        if message_type == "hello":
            self.extension_seen.set()
            return
        request_id = str(message.get("requestId", ""))
        if not request_id:
            return
        with self.pending_lock:
            target = self.pending.get(request_id)
        if target is not None:
            target.put(message)

    def request_cookies(self, timeout: float = 8.0) -> list[dict[str, object]]:
        request_id = uuid.uuid4().hex
        target: queue.Queue[dict[str, object]] = queue.Queue(maxsize=1)
        with self.pending_lock:
            self.pending[request_id] = target
        try:
            self.send(
                {
                    "type": "getCookies",
                    "requestId": request_id,
                    "domains": list(YOUTUBE_COOKIE_DOMAINS),
                }
            )
            response = target.get(timeout=timeout)
        finally:
            with self.pending_lock:
                self.pending.pop(request_id, None)

        if str(response.get("type", "")) == "error":
            raise RuntimeError(str(response.get("error", "Chrome extension returned an error")))
        raw_cookies = response.get("cookies")
        if not isinstance(raw_cookies, list):
            raise RuntimeError("Chrome extension returned an invalid cookie response")
        return [item for item in raw_cookies if isinstance(item, dict)]


class _BridgeHttpServer(ThreadingHTTPServer):
    daemon_threads = True
    allow_reuse_address = True

    def __init__(self, address: tuple[str, int], state: BridgeState) -> None:
        self.state = state
        super().__init__(address, _BridgeRequestHandler)


class _BridgeRequestHandler(BaseHTTPRequestHandler):
    server: _BridgeHttpServer

    def log_message(self, _format: str, *_args: object) -> None:
        return

    def _send_json(self, status: int, payload: dict[str, object]) -> None:
        data = json.dumps(payload, ensure_ascii=False).encode("utf-8")
        self.send_response(status)
        self.send_header("Content-Type", "application/json; charset=utf-8")
        self.send_header("Content-Length", str(len(data)))
        self.send_header("Cache-Control", "no-store")
        self.end_headers()
        self.wfile.write(data)

    def do_GET(self) -> None:
        if self.path != "/health":
            self._send_json(404, {"ok": False})
            return
        self._send_json(200, {"ok": True, "extension_seen": self.server.state.extension_seen.is_set()})

    def do_POST(self) -> None:
        if self.path != "/youtube-cookies":
            self._send_json(404, {"ok": False})
            return
        try:
            cookies = self.server.state.request_cookies()
            cookie_path, count = _write_cookie_file(cookies)
            self._send_json(200, {"ok": True, "path": str(cookie_path), "count": count})
        except queue.Empty:
            self._send_json(504, {"ok": False, "error": "Chrome extension did not answer in time"})
        except Exception as exc:
            self._send_json(500, {"ok": False, "error": str(exc)})


def native_host_main() -> int:
    input_stream = sys.stdin.buffer
    output_stream = sys.stdout.buffer
    state = BridgeState(output_stream)
    try:
        server = _BridgeHttpServer((BRIDGE_HOST, BRIDGE_PORT), state)
    except OSError:
        return 2
    thread = threading.Thread(target=server.serve_forever, name="chrome-bridge-http", daemon=True)
    thread.start()
    try:
        while True:
            message = read_native_message(input_stream)
            if message is None:
                break
            state.handle_extension_message(message)
    except Exception:
        return 3
    finally:
        server.shutdown()
        server.server_close()
    return 0


def register_native_host() -> tuple[bool, str]:
    if os.name != "nt":
        return False, "Chrome bridge registration is currently supported only on Windows."
    host_exe = native_host_executable()
    ext_dir = extension_dir()
    if not host_exe.is_file():
        return False, f"Native host executable was not found: {host_exe}"
    if not (ext_dir / "manifest.json").is_file():
        return False, f"Chrome extension files were not found: {ext_dir}"

    BRIDGE_DIR.mkdir(parents=True, exist_ok=True)
    manifest = {
        "name": HOST_NAME,
        "description": "Mini URL Converter Chrome cookie bridge",
        "path": str(host_exe.resolve()),
        "type": "stdio",
        "allowed_origins": [f"chrome-extension://{EXTENSION_ID}/"],
    }
    NATIVE_MANIFEST_PATH.write_text(json.dumps(manifest, ensure_ascii=False, indent=2), encoding="utf-8")
    try:
        import winreg

        key_path = rf"Software\Google\Chrome\NativeMessagingHosts\{HOST_NAME}"
        with winreg.CreateKey(winreg.HKEY_CURRENT_USER, key_path) as key:
            winreg.SetValueEx(key, "", 0, winreg.REG_SZ, str(NATIVE_MANIFEST_PATH.resolve()))
    except Exception as exc:
        return False, str(exc)
    return True, str(NATIVE_MANIFEST_PATH)


def bridge_health(timeout: float = 0.8) -> bool:
    try:
        with urllib.request.urlopen(f"{BRIDGE_BASE_URL}/health", timeout=timeout) as response:
            payload = json.loads(response.read().decode("utf-8"))
        return bool(isinstance(payload, dict) and payload.get("ok") and payload.get("extension_seen"))
    except Exception:
        return False


def request_live_chrome_cookies(timeout: float = 10.0) -> tuple[Path, int]:
    request = urllib.request.Request(
        f"{BRIDGE_BASE_URL}/youtube-cookies",
        method="POST",
        data=b"{}",
        headers={"Content-Type": "application/json"},
    )
    try:
        with urllib.request.urlopen(request, timeout=timeout) as response:
            payload = json.loads(response.read().decode("utf-8"))
    except urllib.error.HTTPError as exc:
        try:
            detail = json.loads(exc.read().decode("utf-8")).get("error", str(exc))
        except Exception:
            detail = str(exc)
        raise core.AppError(str(detail)) from exc
    except Exception as exc:
        raise core.AppError(str(exc)) from exc

    if not isinstance(payload, dict) or not payload.get("ok"):
        raise core.AppError("Chrome bridge returned an invalid response.")
    path = Path(str(payload.get("path", "")))
    count = int(payload.get("count", 0) or 0)
    if count <= 0 or not path.is_file():
        raise core.AppError("Chrome bridge did not return usable YouTube cookies.")
    return path, count


def open_extension_setup() -> tuple[bool, str]:
    ext_dir = extension_dir()
    if not ext_dir.is_dir():
        return False, f"Chrome extension folder was not found: {ext_dir}"
    try:
        subprocess.Popen(["explorer.exe", str(ext_dir)], close_fds=True)
    except Exception:
        pass

    candidates = [
        Path(os.environ.get("PROGRAMFILES", "")) / "Google" / "Chrome" / "Application" / "chrome.exe",
        Path(os.environ.get("PROGRAMFILES(X86)", "")) / "Google" / "Chrome" / "Application" / "chrome.exe",
        Path(os.environ.get("LOCALAPPDATA", "")) / "Google" / "Chrome" / "Application" / "chrome.exe",
    ]
    chrome = next((path for path in candidates if path.is_file()), None)
    if chrome is None:
        return False, f"Open chrome://extensions and load this folder as an unpacked extension: {ext_dir}"
    try:
        subprocess.Popen([str(chrome), "chrome://extensions/"], close_fds=True)
    except Exception as exc:
        return False, str(exc)
    return True, str(ext_dir)


def self_test() -> list[str]:
    errors: list[str] = []
    sample = {
        "type": "cookiesResponse",
        "requestId": "abc",
        "cookies": [{"domain": ".youtube.com", "path": "/", "name": "SID", "value": "x"}],
    }
    encoded = encode_native_message(sample)
    decoded = read_native_message(io.BytesIO(encoded))
    if decoded != sample:
        errors.append("Native-messaging framing round-trip failed.")
    rendered = serialize_netscape_cookies(
        [
            {
                "domain": ".youtube.com",
                "path": "/",
                "secure": True,
                "httpOnly": True,
                "expirationDate": 2000000000,
                "name": "SID",
                "value": "abc",
            },
            {"domain": ".example.com", "path": "/", "name": "bad", "value": "x"},
        ]
    )
    if "#HttpOnly_.youtube.com\tTRUE\t/\tTRUE\t2000000000\tSID\tabc" not in rendered:
        errors.append("Chrome cookie Netscape serialization failed.")
    if ".example.com" in rendered:
        errors.append("Chrome bridge domain filtering failed.")
    return errors
